#!/bin/bash

USB_PATH=`udevadm info -a -n /dev/tty_astro | egrep "KERNELS==\"[0-9]+\-[0-9/.]+:[0-9/.]+" | cut -d '"' -f 2 | cut -d ':' -f 1`
DEVNUM=`cat /sys/bus/usb/devices/$USB_PATH/devnum`
BUSNUM=`cat /sys/bus/usb/devices/$USB_PATH/busnum`

DEVNUM=`printf %03d $DEVNUM`
BUSNUM=`printf %03d $BUSNUM`

#echo "$BUSNUM $DEVNUM"

MY_PATH="`dirname \"$0\"`"

$MY_PATH/usbreset /dev/bus/usb/$BUSNUM/$DEVNUM
